name: Android CI

on:
  push:
    branches: [ main, master, tests, production ]
  pull_request:
    branches: [ main, master, tests, production ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x SuperWeather/gradlew

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('SuperWeather/**/*.gradle*', 'SuperWeather/**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: |
        cd SuperWeather
        ./gradlew build

    - name: Run Unit Tests
      run: |
        cd SuperWeather
        ./gradlew test

  instrumented-tests:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        api-level: [33]
        target: [default]
        
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x SuperWeather/gradlew
      
    - name: Start Android Emulator and run UI Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: |
          adb wait-for-device
          adb shell input keyevent 82
          cd SuperWeather && ./gradlew connectedAndroidTest --continue